apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapps-deployment
  labels:
    app: myapps
spec:
  replicas: 4 
  
  selector:
    matchLabels:
      app: myapps

  template:
    metadata:
      labels:
        app: myapps
    spec:
      containers:
      - name: myapps-container
        image: calvinstephen/myapp:latest 
        ports:
        - containerPort: 80  
        
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1